[project]
name = "synthetic-data-gen"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pydantic==2.11.7",
    "ollama==0.5.1",
    "tqdm==4.67.1",
    "notebook>=7.4.5",
    "openai==2.16.0",
]
